name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-${{ matrix.os }}-${{ matrix.deno }}
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [windows-latest, ubuntu-latest] # Can't run on macOS because headless isn't working there.
      fail-fast: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache --unstable mod.ts

      - name: Install Chromium
        run: deno run -A --unstable install.ts

      - name: Run tests
        run: deno test -A --unstable tests.ts

      - name: Run tests with lib.dom typings
        run: deno test -A --unstable --config fixtures/dom-tsconfig.json tests.ts
